# Generated by Django 5.2.1 on 2025-06-24 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creci', models.CharField(max_length=150, unique=True)),
                ('descricao', models.CharField(max_length=2000)),
                ('imagem', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('icone', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaixaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pretensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='fci.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cep', models.CharField(max_length=25)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('ponto_referencia', models.CharField(max_length=2000)),
                ('quartos', models.CharField(help_text='Formato permitido: 99 ou 99-99', max_length=5, validators=[django.core.validators.RegexValidator(message='O valor deve estar no formato "99" ou "99-99".', regex='^\\d{2}(-\\d{2})?$')])),
                ('suites', models.CharField(help_text='Formato permitido: 99 ou 99-99', max_length=5, validators=[django.core.validators.RegexValidator(message='O valor deve estar no formato "99" ou "99-99".', regex='^\\d{2}(-\\d{2})?$')])),
                ('banheiros', models.CharField(help_text='Formato permitido: 99 ou 99-99', max_length=5, validators=[django.core.validators.RegexValidator(message='O valor deve estar no formato "99" ou "99-99".', regex='^\\d{2}(-\\d{2})?$')])),
                ('vagas', models.CharField(help_text='Formato permitido: 99 ou 99-99', max_length=5, validators=[django.core.validators.RegexValidator(message='O valor deve estar no formato "99" ou "99-99".', regex='^\\d{2}(-\\d{2})?$')])),
                ('area_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_entrega', models.DateTimeField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='fci.bairro')),
                ('pretensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='fci.pretensao')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='fci.situacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='fci.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to='fci.bairro')),
                ('tipo_imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to='fci.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='fci.uf'),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('cidade', 'nome'), name='bairro_unico_por_cidade'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('uf', 'nome'), name='cidade_unica_por_uf'),
        ),
    ]
