# Generated by Django 5.2.1 on 2025-06-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diferencial',
            name='icone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
