# Generated by Django 5.2.1 on 2025-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fci', '0002_alter_diferencial_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='comentario',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
