# Generated by Django 5.2.1 on 2025-06-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fci', '0003_contato_comentario_contato_respondido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='respondido',
            new_name='status',
        ),
    ]
