# Generated by Django 5.2.1 on 2025-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fci', '0004_rename_respondido_contato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
