# Generated by Django 5.2.1 on 2025-06-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fci', '0005_imovel_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='fci.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('destaque', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=255)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fci.galeria')),
            ],
        ),
        migrations.AddConstraint(
            model_name='galeria',
            constraint=models.UniqueConstraint(fields=('imovel', 'nome'), name='unique_nome_galeria_por_imovel'),
        ),
        migrations.AddConstraint(
            model_name='foto',
            constraint=models.UniqueConstraint(fields=('galeria', 'file_path', 'file_name'), name='foto_unica_por_galeria'),
        ),
    ]
